apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sgr-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: sgr-api.com
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: sgr-api-service
            port:
              number: 80