export enum StatusPedido {
    // AGUARDANDO_CONFIRMACAO_PAGAMENTO = "AGUARDANDO_CONFIRMACAO_PAGAMENTO",
    // RECEBIDO = "RECEBIDO",
    // EM_PREPARACAO = "EM_PREPARACAO",
    // PRONTO = "PRONTO",
    // FINALIZADO = "FINALIZADO",

    AGUARDANDO_CONFIRMACAO_PAGAMENTO = 0,
    RECEBIDO = 1,
    EM_PREPARACAO = 2,
    PRONTO = 3,
    FINALIZADO = 4,
}