export enum StatusPedido {
    RECEBIDO = "RECEBIDO",
    AGUARDANDO_CONFIRMACAO_PAGAMENTO = "AGUARDANDO_CONFIRMACAO_PAGAMENTO",
    PAGO = "PAGO",
    EM_PREPARACAO = "EM_PREPARACAO",
    PRONTO = "PRONTO",
    FINALIZADO = "FINALIZADO",
}