export enum StatusPedido {
    AGUARDANDO_CONFIRMACAO_PAGAMENTO = "AGUARDANDO_CONFIRMACAO_PAGAMENTO",
    RECEBIDO = "RECEBIDO",
    EM_PREPARACAO = "EM_PREPARACAO",
    PRONTO = "PRONTO",
    FINALIZADO = "FINALIZADO",
}