name: Deploy to ECS

on:
  push:
    branches:
      - dev

env:
  AWS_REGION: us-east-2 # set this to your preferred AWS region, e.g. us-west-1
  ECR_REPOSITORY: sgr-service # set this to your Amazon ECR repository name
  ECS_SERVICE: sgr-service # set this to your Amazon ECS service name
  ECS_CLUSTER: sgr-service # set this to your Amazon ECS cluster name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.15.0

      - name: Build Docker image
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t sgr-service:latest .
          aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 190197150713.dkr.ecr.us-east-2.amazonaws.com
          docker tag sgr-service:latest 190197150713.dkr.ecr.us-east-2.amazonaws.com/sgr-service:latest
          docker push 190197150713.dkr.ecr.us-east-2.amazonaws.com/sgr-service:latest

      - name: Deploy to ECS
        run: |
          aws ecs update-service --cluster sgr-service --service sgr-service --force-new-deployment
